[build]
  base = "apps/interviewer-app"
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_KEY = "AIzaSyB0e6gYb3RAEQuHsn-2YTkMc7_FUkp8yIQ"
  VITE_AUTH_DOMAIN = "questionnaire-47fee.firebaseapp.com"
  VITE_PROJECT_ID = "questionnaire-47fee"
  VITE_STORAGE_BUCKET = "questionnaire-47fee.firebasestorage.app"
  VITE_MESSAGING_SENDER_ID = "940663380247"
  VITE_APP_ID = "1:940663380247:web:394dbf5204981a303fff52"
  VITE_MEASUREMENT_ID = "G-BVYWXD5VWC"
